<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el8:
    roles:
      - default
      - ldap_server
      - client
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: <%= hypervisor %>

  el7:
    roles:
      - client
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>

CONFIG:
  log_level: verbose
  type: aio
  vagrant_memsize: 1024
  vagrant_cpus: 2
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
